In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = {
    'study_hours': [2,5,7,3,6,8,4,1,9,5],
    'attendance': [65, 78, 88, 70, 82, 90, 75, 60, 95, 80],
    'previous_mark': [55, 64, 75, 58, 70, 85, 62, 50, 92, 68],
    'final_marks': [58, 72, 84, 62, 78, 90, 68, 52, 95, 74],

}

df = pd.DataFrame(data)
df

   study_hours  attendance  previous_mark  final_marks
0            2          65             55           58
1            5          78             64           72
2            7          88             75           84
3            3          70             58           62
4            6          82             70           78
5            8          90             85           90
6            4          75             62           68
7            1          60             50           52
8            9          95             92           95
9            5          80             68           74

In [3]:
df.head()

   study_hours  attendance  previous_mark  final_marks
0            2          65             55           58
1            5          78             64           72
2            7          88             75           84
3            3          70             58           62
4            6          82             70           78

In [4]:
df.shape

(10, 4)

In [5]:
df.describe()

       study_hours  attendance  previous_mark  final_marks
count    10.000000   10.000000      10.000000    10.000000
mean      5.000000   78.300000      67.900000    73.300000
std       2.581989   11.146001      13.177843    13.872835
min       1.000000   60.000000      50.000000    52.000000
25%       3.250000   71.250000      59.000000    63.500000
50%       5.000000   79.000000      66.000000    73.000000
75%       6.750000   86.500000      73.750000    82.500000
max       9.000000   95.000000      92.000000    95.000000

In [6]:
my_row = {
    'study_hours': 14,
    'attendance': 99,
    'previous_mark': 65,
    'final_marks': 96,
}

df = pd.concat([df, pd.DataFrame([my_row])])
df

   study_hours  attendance  previous_mark  final_marks
0            2          65             55           58
1            5          78             64           72
2            7          88             75           84
3            3          70             58           62
4            6          82             70           78
5            8          90             85           90
6            4          75             62           68
7            1          60             50           52
8            9          95             92           95
9            5          80             68           74
0           14          99             65           96

In [7]:
df = df.drop(columns=['attendace'])
df

KeyError: "['attendace'] not found in axis"

In [ ]:
df = df.drop(columns=['previous_marks'])
df

In [ ]:
# df = df.drop(index=[-1])
# df

df = df.reset_index(drop=True)
df

In [ ]:
df = df.drop(index=[10])
df

In [8]:
df = df.reset_index(drop=True)
df

    study_hours  attendance  previous_mark  final_marks
0             2          65             55           58
1             5          78             64           72
2             7          88             75           84
3             3          70             58           62
4             6          82             70           78
5             8          90             85           90
6             4          75             62           68
7             1          60             50           52
8             9          95             92           95
9             5          80             68           74
10           14          99             65           96

In [9]:
X = df[['study_hours', 'attendance', 'previous_mark']]
y = df['final_marks']

print('Features', X.head())
print('Label', y.head())

Features    study_hours  attendance  previous_mark
0            2          65             55
1            5          78             64
2            7          88             75
3            3          70             58
4            6          82             70
Label 0    58
1    72
2    84
3    62
4    78
Name: final_marks, dtype: int64

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
model = LinearRegression()
model.fit(X,y)
print('Model Ready')

Model Ready

In [13]:
naya_student = [[6, 82, 70]]

predicted = model.predict(naya_student)

# print(predicted)

print(round(predicted[0], 1))

77.4

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [14]:
print("importance(weights)", model.coef_)

importance(weights) [1.35896887 0.55532189 0.32140426]

In [15]:
df['result'] = (df['final_marks'] >= 70).astype(int)

In [16]:
df

    study_hours  attendance  previous_mark  final_marks  result
0             2          65             55           58       0
1             5          78             64           72       1
2             7          88             75           84       1
3             3          70             58           62       0
4             6          82             70           78       1
5             8          90             85           90       1
6             4          75             62           68       0
7             1          60             50           52       0
8             9          95             92           95       1
9             5          80             68           74       1
10           14          99             65           96       1

In [21]:
from sklearn.linear_model import LogisticRegression

In [17]:
X = df[['study_hours', 'attendance', 'previous_mark']]

In [18]:
y = df['result']

In [22]:
clf = LogisticRegression(max_iter=1000)

In [23]:
clf.fit(X,y)

LogisticRegression(max_iter=1000)

In [24]:
print(clf.predict([[5, 80, 65]]))

#[1,60,50]

[1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [29]:
from sklearn.model_selection import train_test_split

In [27]:
X = df[['study_hours','attendance','previous_mark']]
y = df['final_marks']

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size = 0.3, random_state = 42
)

In [31]:
print(len(X_train), len(X_test))

7 4

In [38]:
from sklearn.metrics import mean_absolute_error, r2_score

In [32]:
model = LinearRegression()

In [33]:
model.fit(X_train, y_train)

LinearRegression()

In [34]:
preds = model.predict(X_test)

In [35]:
preds

array([ 89.19224168,  57.25060076,  73.6366289 , 107.88053553])

In [36]:
y_test

5     90
0     58
9     74
10    96
Name: final_marks, dtype: int64

In [39]:
print("Galti (MAE):", round(mean_absolute_error(y_test, preds), 2))

Galti (MAE): 3.45

In [41]:
print('Score R2:', round(r2_score(y_test, preds),2))

Score R2: 0.84