In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = {
    'study_hours': [2,5,7,3,6,8,4,1,9,5],
    'attendance': [65, 78, 88, 70, 82, 90, 75, 60, 95, 80],
    'previous_mark': [55, 64, 75, 58, 70, 85, 62, 50, 92, 68],
    'final_marks': [58, 72, 84, 62, 78, 90, 68, 52, 95, 74],

}

df = pd.DataFrame(data)
df

   study_hours  attendance  previous_mark  final_marks
0            2          65             55           58
1            5          78             64           72
2            7          88             75           84
3            3          70             58           62
4            6          82             70           78
5            8          90             85           90
6            4          75             62           68
7            1          60             50           52
8            9          95             92           95
9            5          80             68           74

In [5]:
df.head()

   study_hours  attendance  previous_mark  final_marks
0            2          65             55           58
1            5          78             64           72
2            7          88             75           84
3            3          70             58           62
4            6          82             70           78

In [6]:
df.shape

(10, 4)

In [7]:
df.describe()

       study_hours  attendance  previous_mark  final_marks
count    10.000000   10.000000      10.000000    10.000000
mean      5.000000   78.300000      67.900000    73.300000
std       2.581989   11.146001      13.177843    13.872835
min       1.000000   60.000000      50.000000    52.000000
25%       3.250000   71.250000      59.000000    63.500000
50%       5.000000   79.000000      66.000000    73.000000
75%       6.750000   86.500000      73.750000    82.500000
max       9.000000   95.000000      92.000000    95.000000

In [9]:
my_row = {
    'study_hours': 14,
    'attendance': 99,
    'previous_mark': 65,
    'final_marks': 96,
}

df = pd.concat([df, pd.DataFrame([my_row])])
df

,study_hours,attendance,previous_mark,final_marks,attendace,previous_marks
0,2,65.0,55.0,58,NaN,NaN
1,5,78.0,64.0,72,NaN,NaN
2,7,88.0,75.0,84,NaN,NaN
3,3,70.0,58.0,62,NaN,NaN
4,6,82.0,70.0,78,NaN,NaN
5,8,90.0,85.0,90,NaN,NaN
6,4,75.0,62.0,68,NaN,NaN
7,1,60.0,50.0,52,NaN,NaN
8,9,95.0,92.0,95,NaN,NaN
9,5,80.0,68.0,74,NaN,NaN
0,14,NaN,NaN,96,99.0,65.0
0,14,99.0,65.0,96,NaN,NaN

In [13]:
df = df.drop(columns=['attendace'])
df

   study_hours  attendance  previous_mark  final_marks  previous_marks
0            2        65.0           55.0           58             NaN
1            5        78.0           64.0           72             NaN
2            7        88.0           75.0           84             NaN
3            3        70.0           58.0           62             NaN
4            6        82.0           70.0           78             NaN
5            8        90.0           85.0           90             NaN
6            4        75.0           62.0           68             NaN
7            1        60.0           50.0           52             NaN
8            9        95.0           92.0           95             NaN
9            5        80.0           68.0           74             NaN
0           14         NaN            NaN           96            65.0
0           14        99.0           65.0           96             NaN

In [14]:
df = df.drop(columns=['previous_marks'])
df

   study_hours  attendance  previous_mark  final_marks
0            2        65.0           55.0           58
1            5        78.0           64.0           72
2            7        88.0           75.0           84
3            3        70.0           58.0           62
4            6        82.0           70.0           78
5            8        90.0           85.0           90
6            4        75.0           62.0           68
7            1        60.0           50.0           52
8            9        95.0           92.0           95
9            5        80.0           68.0           74
0           14         NaN            NaN           96
0           14        99.0           65.0           96

In [16]:
# df = df.drop(index=[-1])
# df

df = df.reset_index(drop=True)
df

    study_hours  attendance  previous_mark  final_marks
0             2        65.0           55.0           58
1             5        78.0           64.0           72
2             7        88.0           75.0           84
3             3        70.0           58.0           62
4             6        82.0           70.0           78
5             8        90.0           85.0           90
6             4        75.0           62.0           68
7             1        60.0           50.0           52
8             9        95.0           92.0           95
9             5        80.0           68.0           74
10           14         NaN            NaN           96
11           14        99.0           65.0           96

In [17]:
df = df.drop(index=[10])
df

    study_hours  attendance  previous_mark  final_marks
0             2        65.0           55.0           58
1             5        78.0           64.0           72
2             7        88.0           75.0           84
3             3        70.0           58.0           62
4             6        82.0           70.0           78
5             8        90.0           85.0           90
6             4        75.0           62.0           68
7             1        60.0           50.0           52
8             9        95.0           92.0           95
9             5        80.0           68.0           74
11           14        99.0           65.0           96

In [18]:
df = df.reset_index(drop=True)
df

    study_hours  attendance  previous_mark  final_marks
0             2        65.0           55.0           58
1             5        78.0           64.0           72
2             7        88.0           75.0           84
3             3        70.0           58.0           62
4             6        82.0           70.0           78
5             8        90.0           85.0           90
6             4        75.0           62.0           68
7             1        60.0           50.0           52
8             9        95.0           92.0           95
9             5        80.0           68.0           74
10           14        99.0           65.0           96

In [19]:
X = df[['study_hours', 'attendance', 'previous_mark']]
y = df['final_marks']

print('Features', X.head())
print('Label', y.head())

Features    study_hours  attendance  previous_mark
0            2        65.0           55.0
1            5        78.0           64.0
2            7        88.0           75.0
3            3        70.0           58.0
4            6        82.0           70.0
Label 0    58
1    72
2    84
3    62
4    78
Name: final_marks, dtype: int64

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
model = LinearRegression()
model.fit(X,y)
print('Model Ready')

Model Ready

In [23]:
naya_student = [[6, 82, 70]]

predicted = model.predict(naya_student)

# print(predicted)

print(round(predicted[0], 1))

77.4

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [24]:
print("importance(weights)", model.coef_)

importance(weights) [1.35896887 0.55532189 0.32140426]