In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vinayaks0n1/ipl-2025")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'ipl-2025' dataset.
Path to dataset files: /kaggle/input/ipl-2025

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
batters = pd.read_csv("/kaggle/input/ipl-2025/IPL2025Batters.csv")

In [6]:
batters.tail()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [11]:
top_5_batters = batters.sort_values("Runs", ascending=False)
top_5_batters

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [10]:
top_5_six_hitters = batters.sort_values("6s", ascending=False)
top_5_six_hitters

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [12]:
bowlers = pd.read_csv("/kaggle/input/ipl-2025/IPL2025Bowlers.csv")

In [14]:
bowlers.head()

,Player Name,Team,WKT,MAT,INN,OVR,RUNS,BBI,AVG,ECO,SR,4W,5W
0,Prasidh Krishna,GT,25,15,15,59.0,488,41/4,19.52,8.27,14.16,1,0
1,Noor Ahmad,CSK,24,14,14,50.0,408,18/4,17.00,8.16,12.50,2,0
2,Josh Hazlewood,RCB,22,12,12,44.0,386,33/4,17.54,8.77,12.00,1,0
3,Trent Boult,MI,22,16,16,57.4,517,26/4,23.50,8.96,15.72,1,0
4,Arshdeep Singh,PBKS,21,17,16,58.2,518,16/3,24.66,8.88,16.66,0,0

In [15]:
top_5_bowlers = bowlers.sort_values("WKT", ascending=False)
top_5_bowlers

,Player Name,Team,WKT,MAT,INN,OVR,RUNS,BBI,AVG,ECO,SR,4W,5W
0,Prasidh Krishna,GT,25,15,15,59.0,488,41/4,19.52,8.27,14.16,1,0
1,Noor Ahmad,CSK,24,14,14,50.0,408,18/4,17.00,8.16,12.50,2,0
2,Josh Hazlewood,RCB,22,12,12,44.0,386,33/4,17.54,8.77,12.00,1,0
3,Trent Boult,MI,22,16,16,57.4,517,26/4,23.50,8.96,15.72,1,0
4,Arshdeep Singh,PBKS,21,17,16,58.2,518,16/3,24.66,8.88,16.66,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,Marcus Stoinis,PBKS,1,13,9,14.1,175,14/1,175.00,12.35,85.00,0,0
104,Shahrukh Khan,GT,1,15,1,1.0,13,13/1,13.00,13.00,6.00,0,0
105,V Satyanarayana Penmetsa,MI,1,2,2,4.0,53,40/1,53.00,13.25,24.00,0,0
106,Musheer Khan,PBKS,1,1,1,2.0,27,27/1,27.00,13.50,12.00,0,0
107,Mujeeb-ur-Rahman,MI,1,1,1,2.0,28,28/1,28.00,14.00,12.00,0,0

In [16]:
batters.shape

(156, 14)

In [17]:
batters[batters["Runs"] > 300]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
13,Aiden Markram,LSG,445,13,13,0,66,34.23,299,148.82,0,5,38,22
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
15,Rohit Sharma,MI,418,15,15,1,81,29.86,280,149.28,0,4,41,22
16,Phil Salt,RCB,403,13,13,1,65,33.58,229,175.98,0,4,48,22
17,Riyan Parag,RR,393,14,14,2,95,32.75,236,166.52,0,1,27,27
18,Ajinkya Rahane,KKR,390,13,12,1,61,35.45,264,147.72,0,3,36,20
19,Ryan Rickelton,MI,388,14,14,1,62*,29.85,257,150.97,0,3,47,17
20,Travis Head,SRH,374,13,12,0,76,31.17,230,162.60,0,3,50,15
21,Nehal Wadhera,PBKS,369,16,15,3,70,30.75,253,145.84,0,2,28,21
22,Shivam Dube,CSK,357,14,14,3,50,32.45,270,132.22,0,1,22,21
23,Ishan Kishan,SRH,354,14,13,3,106*,35.40,232,152.58,1,1,33,15
24,Shashank Singh,PBKS,350,17,14,7,61*,50.00,228,153.50,0,3,23,18
25,N Tilak Varma,MI,343,16,13,2,59,31.18,248,138.30,0,2,23,16
26,Dhruv Jurel,RR,333,14,13,4,70,37.00,213,156.33,0,2,22,22
27,Ayush Badoni,LSG,329,14,11,1,74,32.90,222,148.19,0,2,27,14
28,Rajat Patidar,RCB,312,15,14,1,64,24.00,217,143.77,0,2,25,14
29,Abishek Porel,DC,301,13,13,1,51,25.08,205,146.82,0,1,28,12
30,Ravindra Jadeja,CSK,301,14,14,5,77*,33.44,222,135.58,0,2,25,10

In [19]:
team_runs = batters.groupby("Team")["Runs"].sum().sort_values(ascending=False)
team_runs

Team
PBKS    3000
MI      2802
GT      2766
LSG     2598
RCB     2539
RR      2496
DC      2386
SRH     2378
CSK     2315
KKR     1886
Name: Runs, dtype: int64